name: Reusable run script
on:
  workflow_call:
    inputs:
      script:
        required: true
        type: string
      timeout:
        required: true
        type: number
  
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/run.key
          chmod 600 ~/.ssh/run.key
          cat >> ~/.ssh/config <<EOF
          Host gadi
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/run.key
            StrictHostKeyChecking no
          EOF
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install self
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run Script
        run: ${{ inputs.script }}
        env:
          COSMOS_ACCOUNT_HOST: ${{ secrets.COSMOS_ACCOUNT_HOST }}
          COSMOS_ACCOUNT_KEY: ${{ secrets.COSMOS_ACCOUNT_KEY }}
          COSMOS_DATABASE: ${{ secrets.COSMOS_DATABASE }}
          REMOTE_CMD_HOST: 'gadi'
          REMOTE_FS_KEYS: 'scratch,gdata'
          REMOTE_FS_PATHS: '/scratch,/g/data'
          BLOB_ACCOUNT_HOST: ${{ secrets.BLOB_ACCOUNT_HOST }}
          BLOB_ACCOUNT_KEY: ${{ secrets.BLOB_ACCOUNT_KEY }}
