name: Deploy Function
on:
  push:
    branches: main
env:
  AZURE_FUNCTIONAPP_NAME: 'clex-cms-accounting'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src/clex_functional_accounting/function'
  PYTHON_VERSION: '3.10'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check if function definition or library has changed
      id: changed-func-def
      uses: tj-actions/changed-files@v37
      with:
        files_yaml: |
          funcdeps:
            - src/clex_functional_account/lib/*
            - src/clex_functional_account/function/*

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      if: steps.changed-func-def.outputs.funcdeps_any_changed == 'true'
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install self
      if: steps.changed-func-def.outputs.funcdeps_any_changed == 'true'
      shell: bash
      run: | 
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install ../../../ --target=".python_packages/lib/site-packages"
        popd
    
    - name: Run Azure Functions Action
      uses: Azure/functions-action@v1
      if: steps.changed-func-def.outputs.funcdeps_any_changed == 'true'
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        respect-funcignore: true