name: Gather nci_account data
on:
  schedule:
    - cron: '25 */6 * * *'
  
jobs:
  call-common:
    uses: ./.github/workflows/common.yml
    with:
      script: update_nci_account
    secrets: inherit