name: Gather User and Group Data
on:
  schedule:
    - cron: '5 */6 * * *'
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/run.key
          chmod 600 ~/.ssh/run.key
          cat >> ~/.ssh/config <<EOF
          Host gadi
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/run.key
            StrictHostKeyChecking no
          EOF
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Script
        run: python3 ./update_users_and_projects.py
        env:
          COSMOS_ACCOUNT_HOST: ${{ secrets.COSMOS_ACCOUNT_HOST }}
          COSMOS_ACCOUNT_KEY: ${{ secrets.COSMOS_ACCOUNT_KEY }}
          COSMOS_DATABASE: ${{ secrets.COSMOS_DATABASE }}
          REMOTE_CMD_HOST: 'gadi'
