name: Gather User and Group data
on:
  schedule:
    - cron: '5 */6 * * *'
  
jobs:
  call-common:
    uses: ./.github/workflows/common.yml
    with:
      script: update_users_and_projects
    secrets: inherit